import os
from sqlalchemy.orm import Session
from backend.database import SessionLocal, engine, Base
from backend.models.commodity import Commodity
from backend.models.polymer import Polymer
from backend.models.user import User
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(password):
    return pwd_context.hash(password)

def seed_database():
    print("Creating tables...")
    Base.metadata.create_all(bind=engine)
    
    db: Session = SessionLocal()
    
    try:
        # Check if users already exist
        if db.query(User).first():
            print("Database is already seeded.")
            return

        print("Seeding Users...")
        users = [
            User(username="admin", email="admin@packaging.ai", hashed_password=get_password_hash("Admin@123"), role="ADMIN"),
            User(username="analyst", email="analyst@packaging.ai", hashed_password=get_password_hash("Analyst@123"), role="ANALYST"),
            User(username="farmer", email="farmer@packaging.ai", hashed_password=get_password_hash("Farmer@123"), role="FARMER_USER")
        ]
        db.add_all(users)

        print("Seeding Commodities...")
        commodities_data = [
            # Category 1: Fresh Horticulture
            {"name": "Alphonso Mango", "category": "Fresh Horticulture", "initial_moisture_pct": 82.0, "critical_moisture_pct": 75.0, "water_activity_aw": 0.98, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 15.0, "km_o2": 2.5, "optimal_temp_min": 10.0, "optimal_temp_max": 13.0, "max_tolerable_o2_uptake": 1200.0},
            {"name": "Banana (Cavendish)", "category": "Fresh Horticulture", "initial_moisture_pct": 74.0, "critical_moisture_pct": 68.0, "water_activity_aw": 0.97, "lipid_pct": 0.3, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "High", "vm_o2": 30.0, "km_o2": 1.5, "optimal_temp_min": 13.0, "optimal_temp_max": 15.0, "max_tolerable_o2_uptake": 1500.0},
            {"name": "Papaya", "category": "Fresh Horticulture", "initial_moisture_pct": 88.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.99, "lipid_pct": 0.1, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 12.0, "km_o2": 2.0, "optimal_temp_min": 10.0, "optimal_temp_max": 12.0, "max_tolerable_o2_uptake": 1000.0},
            {"name": "Guava (Allahabad)", "category": "Fresh Horticulture", "initial_moisture_pct": 80.0, "critical_moisture_pct": 73.0, "water_activity_aw": 0.98, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "High", "vm_o2": 25.0, "km_o2": 2.0, "optimal_temp_min": 8.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 1300.0},
            {"name": "Pineapple", "category": "Fresh Horticulture", "initial_moisture_pct": 86.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.99, "lipid_pct": 0.1, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 8.0, "km_o2": 3.0, "optimal_temp_min": 7.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 800.0},
            {"name": "Litchi", "category": "Fresh Horticulture", "initial_moisture_pct": 81.0, "critical_moisture_pct": 75.0, "water_activity_aw": 0.98, "lipid_pct": 0.4, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 18.0, "km_o2": 1.5, "optimal_temp_min": 2.0, "optimal_temp_max": 5.0, "max_tolerable_o2_uptake": 900.0},
            {"name": "Jackfruit", "category": "Fresh Horticulture", "initial_moisture_pct": 73.0, "critical_moisture_pct": 68.0, "water_activity_aw": 0.97, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "High", "vm_o2": 28.0, "km_o2": 2.5, "optimal_temp_min": 11.0, "optimal_temp_max": 13.0, "max_tolerable_o2_uptake": 1400.0},
            {"name": "Sapota (Chikoo)", "category": "Fresh Horticulture", "initial_moisture_pct": 77.0, "critical_moisture_pct": 70.0, "water_activity_aw": 0.98, "lipid_pct": 1.1, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 15.0, "km_o2": 2.0, "optimal_temp_min": 12.0, "optimal_temp_max": 14.0, "max_tolerable_o2_uptake": 1100.0},
            {"name": "Custard Apple", "category": "Fresh Horticulture", "initial_moisture_pct": 73.0, "critical_moisture_pct": 65.0, "water_activity_aw": 0.97, "lipid_pct": 0.5, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Very High", "vm_o2": 45.0, "km_o2": 2.0, "optimal_temp_min": 15.0, "optimal_temp_max": 20.0, "max_tolerable_o2_uptake": 2000.0},
            {"name": "Star Fruit", "category": "Fresh Horticulture", "initial_moisture_pct": 91.0, "critical_moisture_pct": 85.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 14.0, "km_o2": 2.5, "optimal_temp_min": 5.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 1200.0},
            {"name": "Kinnow Mandarin", "category": "Fresh Horticulture", "initial_moisture_pct": 87.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 6.0, "km_o2": 3.0, "optimal_temp_min": 4.0, "optimal_temp_max": 6.0, "max_tolerable_o2_uptake": 700.0},
            {"name": "Nagpur Orange", "category": "Fresh Horticulture", "initial_moisture_pct": 86.0, "critical_moisture_pct": 79.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 6.0, "km_o2": 3.0, "optimal_temp_min": 4.0, "optimal_temp_max": 7.0, "max_tolerable_o2_uptake": 700.0},
            {"name": "Mosambi (Sweet Lime)", "category": "Fresh Horticulture", "initial_moisture_pct": 89.0, "critical_moisture_pct": 82.0, "water_activity_aw": 0.99, "lipid_pct": 0.1, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 5.0, "km_o2": 3.0, "optimal_temp_min": 5.0, "optimal_temp_max": 8.0, "max_tolerable_o2_uptake": 650.0},
            {"name": "Pomegranate", "category": "Fresh Horticulture", "initial_moisture_pct": 77.0, "critical_moisture_pct": 70.0, "water_activity_aw": 0.98, "lipid_pct": 1.2, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 4.0, "km_o2": 2.0, "optimal_temp_min": 5.0, "optimal_temp_max": 8.0, "max_tolerable_o2_uptake": 600.0},
            {"name": "Fig (Poona)", "category": "Fresh Horticulture", "initial_moisture_pct": 79.0, "critical_moisture_pct": 72.0, "water_activity_aw": 0.98, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 16.0, "km_o2": 1.5, "optimal_temp_min": -1.0, "optimal_temp_max": 1.0, "max_tolerable_o2_uptake": 1000.0},
            {"name": "Red Globe Grape", "category": "Fresh Horticulture", "initial_moisture_pct": 81.0, "critical_moisture_pct": 76.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 3.0, "km_o2": 2.0, "optimal_temp_min": -1.0, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 550.0},
            {"name": "Thompson Seedless Grape", "category": "Fresh Horticulture", "initial_moisture_pct": 81.0, "critical_moisture_pct": 76.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 3.0, "km_o2": 2.0, "optimal_temp_min": -1.0, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 550.0},
            {"name": "Kashmiri Apple (Red Delicious)", "category": "Fresh Horticulture", "initial_moisture_pct": 85.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 2.5, "km_o2": 1.0, "optimal_temp_min": -1.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 500.0},
            {"name": "Shimla Apple (Royal Gala)", "category": "Fresh Horticulture", "initial_moisture_pct": 86.0, "critical_moisture_pct": 81.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 2.5, "km_o2": 1.0, "optimal_temp_min": -1.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 500.0},
            {"name": "Pear (Bartlett)", "category": "Fresh Horticulture", "initial_moisture_pct": 84.0, "critical_moisture_pct": 78.0, "water_activity_aw": 0.98, "lipid_pct": 0.1, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 3.5, "km_o2": 1.2, "optimal_temp_min": -1.0, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 600.0},
            {"name": "Apricot (Ladakh)", "category": "Fresh Horticulture", "initial_moisture_pct": 86.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.98, "lipid_pct": 0.4, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 12.0, "km_o2": 1.5, "optimal_temp_min": -0.5, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 900.0},
            {"name": "Cherry (Srinagar)", "category": "Fresh Horticulture", "initial_moisture_pct": 82.0, "critical_moisture_pct": 77.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 10.0, "km_o2": 1.5, "optimal_temp_min": -1.0, "optimal_temp_max": -0.5, "max_tolerable_o2_uptake": 850.0},
            {"name": "Plum (Santa Rosa)", "category": "Fresh Horticulture", "initial_moisture_pct": 87.0, "critical_moisture_pct": 82.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 11.0, "km_o2": 1.5, "optimal_temp_min": -0.5, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 950.0},
            {"name": "Kiwi (Arunachal)", "category": "Fresh Horticulture", "initial_moisture_pct": 83.0, "critical_moisture_pct": 78.0, "water_activity_aw": 0.98, "lipid_pct": 0.5, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Low", "vm_o2": 5.0, "km_o2": 2.0, "optimal_temp_min": -0.5, "optimal_temp_max": 0.0, "max_tolerable_o2_uptake": 700.0},
            {"name": "Strawberry (Mahabaleshwar)", "category": "Fresh Horticulture", "initial_moisture_pct": 91.0, "critical_moisture_pct": 85.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Extremely High", "vm_o2": 55.0, "km_o2": 1.5, "optimal_temp_min": 0.0, "optimal_temp_max": 1.0, "max_tolerable_o2_uptake": 3000.0},
            {"name": "Tomato", "category": "Fresh Horticulture", "initial_moisture_pct": 94.0, "critical_moisture_pct": 88.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 12.0, "km_o2": 2.5, "optimal_temp_min": 10.0, "optimal_temp_max": 15.0, "max_tolerable_o2_uptake": 1100.0},
            {"name": "Okra", "category": "Fresh Horticulture", "initial_moisture_pct": 90.0, "critical_moisture_pct": 84.0, "water_activity_aw": 0.99, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "High", "vm_o2": 35.0, "km_o2": 3.0, "optimal_temp_min": 7.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 1600.0},
            {"name": "Green Chilli", "category": "Fresh Horticulture", "initial_moisture_pct": 88.0, "critical_moisture_pct": 82.0, "water_activity_aw": 0.99, "lipid_pct": 0.4, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 18.0, "km_o2": 2.0, "optimal_temp_min": 7.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 1250.0},
            {"name": "Capsicum (Bell Pepper)", "category": "Fresh Horticulture", "initial_moisture_pct": 92.0, "critical_moisture_pct": 87.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "Moderate", "vm_o2": 15.0, "km_o2": 2.5, "optimal_temp_min": 7.0, "optimal_temp_max": 10.0, "max_tolerable_o2_uptake": 1200.0},
            {"name": "Broccoli", "category": "Fresh Horticulture", "initial_moisture_pct": 89.0, "critical_moisture_pct": 83.0, "water_activity_aw": 0.99, "lipid_pct": 0.4, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "Extremely High", "vm_o2": 60.0, "km_o2": 1.5, "optimal_temp_min": 0.0, "optimal_temp_max": 2.0, "max_tolerable_o2_uptake": 3500.0},
            {"name": "Mushroom (Button)", "category": "Fresh Horticulture", "initial_moisture_pct": 92.0, "critical_moisture_pct": 88.0, "water_activity_aw": 0.99, "lipid_pct": 0.3, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "Extremely High", "vm_o2": 80.0, "km_o2": 1.0, "optimal_temp_min": 0.0, "optimal_temp_max": 2.0, "max_tolerable_o2_uptake": 4500.0},
            {"name": "Spinach", "category": "Fresh Horticulture", "initial_moisture_pct": 91.0, "critical_moisture_pct": 85.0, "water_activity_aw": 0.99, "lipid_pct": 0.4, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "Extremely High", "vm_o2": 50.0, "km_o2": 1.5, "optimal_temp_min": 0.0, "optimal_temp_max": 2.0, "max_tolerable_o2_uptake": 3200.0},
            {"name": "Drumstick (Moringa Pod)", "category": "Fresh Horticulture", "initial_moisture_pct": 86.0, "critical_moisture_pct": 80.0, "water_activity_aw": 0.98, "lipid_pct": 0.2, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "High", "vm_o2": 25.0, "km_o2": 2.0, "optimal_temp_min": 10.0, "optimal_temp_max": 12.0, "max_tolerable_o2_uptake": 1500.0},

            # Category 2: High-Lipid Snacks
            {"name": "Potato Chips (Salted)", "category": "High-Lipid Snacks", "initial_moisture_pct": 2.0, "critical_moisture_pct": 6.0, "water_activity_aw": 0.2, "lipid_pct": 35.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 100.0},
            {"name": "Masala Potato Chips", "category": "High-Lipid Snacks", "initial_moisture_pct": 2.5, "critical_moisture_pct": 6.5, "water_activity_aw": 0.25, "lipid_pct": 33.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 120.0},
            {"name": "Banana Chips", "category": "High-Lipid Snacks", "initial_moisture_pct": 3.0, "critical_moisture_pct": 7.0, "water_activity_aw": 0.3, "lipid_pct": 30.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 150.0},
            {"name": "Tapioca Chips", "category": "High-Lipid Snacks", "initial_moisture_pct": 2.5, "critical_moisture_pct": 6.5, "water_activity_aw": 0.25, "lipid_pct": 28.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 180.0},
            {"name": "Namkeen Mix (Haldiram's type)", "category": "High-Lipid Snacks", "initial_moisture_pct": 4.0, "critical_moisture_pct": 8.0, "water_activity_aw": 0.35, "lipid_pct": 38.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 150.0},
            {"name": "Fried Dal (Moong)", "category": "High-Lipid Snacks", "initial_moisture_pct": 3.5, "critical_moisture_pct": 7.5, "water_activity_aw": 0.3, "lipid_pct": 22.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 200.0},
            {"name": "Peanut Chikki", "category": "High-Lipid Snacks", "initial_moisture_pct": 4.5, "critical_moisture_pct": 9.0, "water_activity_aw": 0.4, "lipid_pct": 25.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 250.0},
            {"name": "Cashew Nut (Roasted Salted)", "category": "High-Lipid Snacks", "initial_moisture_pct": 2.0, "critical_moisture_pct": 6.0, "water_activity_aw": 0.2, "lipid_pct": 45.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 120.0},
            {"name": "Almond (Blanched)", "category": "High-Lipid Snacks", "initial_moisture_pct": 4.0, "critical_moisture_pct": 8.0, "water_activity_aw": 0.35, "lipid_pct": 49.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 200.0},
            {"name": "Kurkure-type Extruded Snack", "category": "High-Lipid Snacks", "initial_moisture_pct": 2.0, "critical_moisture_pct": 5.5, "water_activity_aw": 0.2, "lipid_pct": 32.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 130.0},
            {"name": "Murukku (Rice Spiral)", "category": "High-Lipid Snacks", "initial_moisture_pct": 3.0, "critical_moisture_pct": 7.0, "water_activity_aw": 0.25, "lipid_pct": 26.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 180.0},
            {"name": "Chakli", "category": "High-Lipid Snacks", "initial_moisture_pct": 3.5, "critical_moisture_pct": 7.5, "water_activity_aw": 0.3, "lipid_pct": 24.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 30.0, "max_tolerable_o2_uptake": 190.0},

            # Category 3: Dairy & Fat Emulsions
            {"name": "Paneer (Fresh)", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 55.0, "critical_moisture_pct": 50.0, "water_activity_aw": 0.99, "lipid_pct": 25.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 2.0, "optimal_temp_max": 5.0, "max_tolerable_o2_uptake": 300.0},
            {"name": "Ghee (Clarified Butter)", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 0.5, "critical_moisture_pct": 1.0, "water_activity_aw": 0.1, "lipid_pct": 99.5, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 50.0},
            {"name": "White Butter (Unsalted)", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 16.0, "critical_moisture_pct": 18.0, "water_activity_aw": 0.9, "lipid_pct": 82.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 2.0, "optimal_temp_max": 6.0, "max_tolerable_o2_uptake": 80.0},
            {"name": "Cheddar Cheese", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 36.0, "critical_moisture_pct": 32.0, "water_activity_aw": 0.95, "lipid_pct": 33.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 4.0, "optimal_temp_max": 8.0, "max_tolerable_o2_uptake": 150.0},
            {"name": "Processed Cheese Spread", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 52.0, "critical_moisture_pct": 48.0, "water_activity_aw": 0.97, "lipid_pct": 23.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 4.0, "optimal_temp_max": 8.0, "max_tolerable_o2_uptake": 200.0},
            {"name": "Skimmed Milk Powder", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 4.0, "critical_moisture_pct": 6.0, "water_activity_aw": 0.2, "lipid_pct": 0.5, "oxidation_sensitivity": "Low", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 1000.0},
            {"name": "Whole Milk Powder", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 3.0, "critical_moisture_pct": 5.0, "water_activity_aw": 0.2, "lipid_pct": 26.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 120.0},
            {"name": "Khoa (Mawa)", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 30.0, "critical_moisture_pct": 25.0, "water_activity_aw": 0.94, "lipid_pct": 20.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 2.0, "optimal_temp_max": 6.0, "max_tolerable_o2_uptake": 250.0},
            {"name": "Dahi (Yogurt)", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 85.0, "critical_moisture_pct": 82.0, "water_activity_aw": 0.99, "lipid_pct": 4.0, "oxidation_sensitivity": "Low", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 2.0, "optimal_temp_max": 5.0, "max_tolerable_o2_uptake": 800.0},
            {"name": "Condensed Milk", "category": "Dairy & Fat Emulsions", "initial_moisture_pct": 26.0, "critical_moisture_pct": 28.0, "water_activity_aw": 0.85, "lipid_pct": 8.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 10.0, "optimal_temp_max": 20.0, "max_tolerable_o2_uptake": 500.0},

            # Category 4: Bakery & Confectionery
            {"name": "White Bread (Sliced)", "category": "Bakery & Confectionery", "initial_moisture_pct": 38.0, "critical_moisture_pct": 30.0, "water_activity_aw": 0.96, "lipid_pct": 3.0, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 1000.0},
            {"name": "Whole Wheat Bread", "category": "Bakery & Confectionery", "initial_moisture_pct": 39.0, "critical_moisture_pct": 32.0, "water_activity_aw": 0.96, "lipid_pct": 4.0, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 800.0},
            {"name": "Cream Biscuit", "category": "Bakery & Confectionery", "initial_moisture_pct": 3.0, "critical_moisture_pct": 6.0, "water_activity_aw": 0.25, "lipid_pct": 22.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 300.0},
            {"name": "Glucose Biscuit", "category": "Bakery & Confectionery", "initial_moisture_pct": 4.0, "critical_moisture_pct": 7.0, "water_activity_aw": 0.3, "lipid_pct": 12.0, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 500.0},
            {"name": "Cake Rusk", "category": "Bakery & Confectionery", "initial_moisture_pct": 5.0, "critical_moisture_pct": 8.0, "water_activity_aw": 0.35, "lipid_pct": 15.0, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 20.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 400.0},
            {"name": "Fruit Cake", "category": "Bakery & Confectionery", "initial_moisture_pct": 22.0, "critical_moisture_pct": 18.0, "water_activity_aw": 0.82, "lipid_pct": 18.0, "oxidation_sensitivity": "High", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 20.0, "max_tolerable_o2_uptake": 350.0},
            {"name": "Naan (Frozen)", "category": "Bakery & Confectionery", "initial_moisture_pct": 35.0, "critical_moisture_pct": 30.0, "water_activity_aw": 0.95, "lipid_pct": 5.0, "oxidation_sensitivity": "Low", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": -18.0, "optimal_temp_max": -15.0, "max_tolerable_o2_uptake": 800.0},
            {"name": "Milk Chocolate Bar", "category": "Bakery & Confectionery", "initial_moisture_pct": 1.5, "critical_moisture_pct": 3.0, "water_activity_aw": 0.3, "lipid_pct": 30.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 18.0, "optimal_temp_max": 22.0, "max_tolerable_o2_uptake": 400.0},
            {"name": "Dark Chocolate (70%)", "category": "Bakery & Confectionery", "initial_moisture_pct": 1.0, "critical_moisture_pct": 2.5, "water_activity_aw": 0.25, "lipid_pct": 40.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 18.0, "optimal_temp_max": 22.0, "max_tolerable_o2_uptake": 450.0},
            {"name": "Barfi (Milk Sweet)", "category": "Bakery & Confectionery", "initial_moisture_pct": 15.0, "critical_moisture_pct": 12.0, "water_activity_aw": 0.75, "lipid_pct": 15.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 10.0, "optimal_temp_max": 15.0, "max_tolerable_o2_uptake": 300.0},

            # Category 5: Meat/Poultry/Seafood
            {"name": "Chicken Breast (Fresh)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 74.0, "critical_moisture_pct": 68.0, "water_activity_aw": 0.99, "lipid_pct": 3.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 150.0},
            {"name": "Chicken Drumstick (Frozen)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 72.0, "critical_moisture_pct": 65.0, "water_activity_aw": 0.99, "lipid_pct": 8.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": -18.0, "optimal_temp_max": -15.0, "max_tolerable_o2_uptake": 120.0},
            {"name": "Mutton Mince (Fresh)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 70.0, "critical_moisture_pct": 62.0, "water_activity_aw": 0.99, "lipid_pct": 15.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 100.0},
            {"name": "Buffalo Meat (Frozen)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 73.0, "critical_moisture_pct": 68.0, "water_activity_aw": 0.99, "lipid_pct": 6.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": -18.0, "optimal_temp_max": -15.0, "max_tolerable_o2_uptake": 130.0},
            {"name": "Pork Sausage", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 60.0, "critical_moisture_pct": 55.0, "water_activity_aw": 0.97, "lipid_pct": 25.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 80.0},
            {"name": "Rohu Fish Fillet", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 78.0, "critical_moisture_pct": 72.0, "water_activity_aw": 0.99, "lipid_pct": 2.5, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 2.0, "max_tolerable_o2_uptake": 90.0},
            {"name": "Pomfret (Whole)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 76.0, "critical_moisture_pct": 70.0, "water_activity_aw": 0.99, "lipid_pct": 4.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 2.0, "max_tolerable_o2_uptake": 80.0},
            {"name": "Tiger Prawn (Frozen)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 79.0, "critical_moisture_pct": 75.0, "water_activity_aw": 0.99, "lipid_pct": 1.5, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": -18.0, "optimal_temp_max": -15.0, "max_tolerable_o2_uptake": 110.0},
            {"name": "Surimi (Fish Paste)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 75.0, "critical_moisture_pct": 70.0, "water_activity_aw": 0.98, "lipid_pct": 1.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": -18.0, "optimal_temp_max": -10.0, "max_tolerable_o2_uptake": 150.0},
            {"name": "Egg (Liquid Pasteurized)", "category": "Meat/Poultry/Seafood", "initial_moisture_pct": 75.0, "critical_moisture_pct": 72.0, "water_activity_aw": 0.99, "lipid_pct": 10.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 0.0, "optimal_temp_max": 4.0, "max_tolerable_o2_uptake": 120.0},

            # Category 6: Spices & High-Volatile Condiments
            {"name": "Turmeric Powder", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 9.0, "critical_moisture_pct": 13.0, "water_activity_aw": 0.45, "lipid_pct": 5.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 400.0},
            {"name": "Red Chilli Powder", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 10.0, "critical_moisture_pct": 14.0, "water_activity_aw": 0.5, "lipid_pct": 12.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 300.0},
            {"name": "Cumin (Whole)", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 8.0, "critical_moisture_pct": 12.0, "water_activity_aw": 0.4, "lipid_pct": 15.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 250.0},
            {"name": "Black Pepper (Whole)", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 11.0, "critical_moisture_pct": 15.0, "water_activity_aw": 0.55, "lipid_pct": 8.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 350.0},
            {"name": "Cardamom (Green)", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 10.0, "critical_moisture_pct": 13.0, "water_activity_aw": 0.5, "lipid_pct": 6.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 20.0, "max_tolerable_o2_uptake": 200.0},
            {"name": "Cinnamon Sticks", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 12.0, "critical_moisture_pct": 16.0, "water_activity_aw": 0.6, "lipid_pct": 3.0, "oxidation_sensitivity": "Medium", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 450.0},
            {"name": "Coriander Powder", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 8.5, "critical_moisture_pct": 12.5, "water_activity_aw": 0.42, "lipid_pct": 14.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 280.0},
            {"name": "Garam Masala Blend", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 9.5, "critical_moisture_pct": 13.5, "water_activity_aw": 0.48, "lipid_pct": 10.0, "oxidation_sensitivity": "High", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 260.0},
            {"name": "Fenugreek Seeds", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 7.0, "critical_moisture_pct": 11.0, "water_activity_aw": 0.35, "lipid_pct": 7.0, "oxidation_sensitivity": "Medium", "light_sensitivity": False, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 15.0, "optimal_temp_max": 25.0, "max_tolerable_o2_uptake": 500.0},
            {"name": "Asafoetida (Hing)", "category": "Spices & High-Volatile Condiments", "initial_moisture_pct": 5.0, "critical_moisture_pct": 10.0, "water_activity_aw": 0.3, "lipid_pct": 16.0, "oxidation_sensitivity": "Critical", "light_sensitivity": True, "respiration_class": "None", "vm_o2": 0.0, "km_o2": 0.0, "optimal_temp_min": 10.0, "optimal_temp_max": 20.0, "max_tolerable_o2_uptake": 150.0}
        ]

        for item in commodities_data:
            db.add(Commodity(**item))

        print("Seeding Polymers...")
        polymers_data = [
            {"name": "LDPE", "category_type": "Monolayer", "nominal_thickness_um": 50, "baseline_wvtr": 18.0, "baseline_otr": 7000.0, "co2_permeability": 25000.0, "activation_energy_wvtr": 35.0, "activation_energy_otr": 40.0, "puncture_resistance_N": 15.0, "seal_initiation_temp_C": 110.0, "optical_haze_pct": 8.0, "cost_per_kg_inr": 130.0, "carbon_footprint_kgCO2": 2.0, "recyclability_class": "A", "fssai_certified": True},
            {"name": "LLDPE", "category_type": "Heat Sealant Layer", "nominal_thickness_um": 40, "baseline_wvtr": 15.0, "baseline_otr": 7500.0, "co2_permeability": 27000.0, "activation_energy_wvtr": 36.0, "activation_energy_otr": 41.0, "puncture_resistance_N": 25.0, "seal_initiation_temp_C": 105.0, "optical_haze_pct": 10.0, "cost_per_kg_inr": 135.0, "carbon_footprint_kgCO2": 2.1, "recyclability_class": "A", "fssai_certified": True},
            {"name": "Metallocene LLDPE", "category_type": "Heat Sealant Layer", "nominal_thickness_um": 30, "baseline_wvtr": 12.0, "baseline_otr": 6800.0, "co2_permeability": 24000.0, "activation_energy_wvtr": 36.0, "activation_energy_otr": 41.0, "puncture_resistance_N": 35.0, "seal_initiation_temp_C": 95.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 160.0, "carbon_footprint_kgCO2": 2.2, "recyclability_class": "A", "fssai_certified": True},
            {"name": "HDPE", "category_type": "Monolayer", "nominal_thickness_um": 40, "baseline_wvtr": 7.0, "baseline_otr": 2500.0, "co2_permeability": 9000.0, "activation_energy_wvtr": 38.0, "activation_energy_otr": 43.0, "puncture_resistance_N": 20.0, "seal_initiation_temp_C": 130.0, "optical_haze_pct": 25.0, "cost_per_kg_inr": 140.0, "carbon_footprint_kgCO2": 1.9, "recyclability_class": "A", "fssai_certified": True},
            {"name": "BOPP", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 20, "baseline_wvtr": 5.5, "baseline_otr": 1600.0, "co2_permeability": 6000.0, "activation_energy_wvtr": 40.0, "activation_energy_otr": 45.0, "puncture_resistance_N": 12.0, "seal_initiation_temp_C": 140.0, "optical_haze_pct": 2.0, "cost_per_kg_inr": 150.0, "carbon_footprint_kgCO2": 2.0, "recyclability_class": "A", "fssai_certified": True},
            {"name": "Metallized BOPP", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 20, "baseline_wvtr": 0.8, "baseline_otr": 65.0, "co2_permeability": 200.0, "activation_energy_wvtr": 42.0, "activation_energy_otr": 48.0, "puncture_resistance_N": 12.0, "seal_initiation_temp_C": 140.0, "optical_haze_pct": 95.0, "cost_per_kg_inr": 260.0, "carbon_footprint_kgCO2": 2.8, "recyclability_class": "D", "fssai_certified": True},
            {"name": "PET", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 12, "baseline_wvtr": 16.0, "baseline_otr": 65.0, "co2_permeability": 250.0, "activation_energy_wvtr": 42.0, "activation_energy_otr": 38.0, "puncture_resistance_N": 28.0, "seal_initiation_temp_C": 250.0, "optical_haze_pct": 3.0, "cost_per_kg_inr": 220.0, "carbon_footprint_kgCO2": 3.5, "recyclability_class": "B", "fssai_certified": True},
            {"name": "Metallized PET", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 12, "baseline_wvtr": 0.4, "baseline_otr": 0.8, "co2_permeability": 3.0, "activation_energy_wvtr": 45.0, "activation_energy_otr": 40.0, "puncture_resistance_N": 28.0, "seal_initiation_temp_C": 250.0, "optical_haze_pct": 97.0, "cost_per_kg_inr": 350.0, "carbon_footprint_kgCO2": 4.2, "recyclability_class": "D", "fssai_certified": True},
            {"name": "CPP", "category_type": "Heat Sealant Layer", "nominal_thickness_um": 30, "baseline_wvtr": 9.0, "baseline_otr": 2800.0, "co2_permeability": 10000.0, "activation_energy_wvtr": 38.0, "activation_energy_otr": 44.0, "puncture_resistance_N": 18.0, "seal_initiation_temp_C": 120.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 155.0, "carbon_footprint_kgCO2": 2.1, "recyclability_class": "A", "fssai_certified": True},
            {"name": "EVOH", "category_type": "Barrier Core Layer", "nominal_thickness_um": 15, "baseline_wvtr": 13.5, "baseline_otr": 0.08, "co2_permeability": 0.2, "activation_energy_wvtr": 30.0, "activation_energy_otr": 60.0, "puncture_resistance_N": 22.0, "seal_initiation_temp_C": 165.0, "optical_haze_pct": 4.0, "cost_per_kg_inr": 1200.0, "carbon_footprint_kgCO2": 4.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "Nylon-6", "category_type": "Barrier Core Layer", "nominal_thickness_um": 15, "baseline_wvtr": 150.0, "baseline_otr": 30.0, "co2_permeability": 120.0, "activation_energy_wvtr": 25.0, "activation_energy_otr": 50.0, "puncture_resistance_N": 40.0, "seal_initiation_temp_C": 220.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 300.0, "carbon_footprint_kgCO2": 8.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "PVDC", "category_type": "Barrier Core Layer", "nominal_thickness_um": 15, "baseline_wvtr": 1.5, "baseline_otr": 5.0, "co2_permeability": 20.0, "activation_energy_wvtr": 45.0, "activation_energy_otr": 55.0, "puncture_resistance_N": 15.0, "seal_initiation_temp_C": 140.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 1000.0, "carbon_footprint_kgCO2": 6.0, "recyclability_class": "E", "fssai_certified": True},
            {"name": "Aluminum Foil (7μm)", "category_type": "Barrier Core Layer", "nominal_thickness_um": 7, "baseline_wvtr": 0.0, "baseline_otr": 0.0, "co2_permeability": 0.0, "activation_energy_wvtr": 0.0, "activation_energy_otr": 0.0, "puncture_resistance_N": 8.0, "seal_initiation_temp_C": 600.0, "optical_haze_pct": 100.0, "cost_per_kg_inr": 450.0, "carbon_footprint_kgCO2": 11.0, "recyclability_class": "C", "fssai_certified": True},
            {"name": "Aluminum Foil (9μm)", "category_type": "Barrier Core Layer", "nominal_thickness_um": 9, "baseline_wvtr": 0.0, "baseline_otr": 0.0, "co2_permeability": 0.0, "activation_energy_wvtr": 0.0, "activation_energy_otr": 0.0, "puncture_resistance_N": 10.0, "seal_initiation_temp_C": 600.0, "optical_haze_pct": 100.0, "cost_per_kg_inr": 500.0, "carbon_footprint_kgCO2": 11.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "PLA", "category_type": "Monolayer", "nominal_thickness_um": 25, "baseline_wvtr": 250.0, "baseline_otr": 650.0, "co2_permeability": 2500.0, "activation_energy_wvtr": 30.0, "activation_energy_otr": 35.0, "puncture_resistance_N": 10.0, "seal_initiation_temp_C": 80.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 450.0, "carbon_footprint_kgCO2": 1.8, "recyclability_class": "F", "fssai_certified": True},
            {"name": "PBAT", "category_type": "Monolayer", "nominal_thickness_um": 25, "baseline_wvtr": 350.0, "baseline_otr": 850.0, "co2_permeability": 3000.0, "activation_energy_wvtr": 32.0, "activation_energy_otr": 36.0, "puncture_resistance_N": 15.0, "seal_initiation_temp_C": 90.0, "optical_haze_pct": 15.0, "cost_per_kg_inr": 500.0, "carbon_footprint_kgCO2": 2.0, "recyclability_class": "F", "fssai_certified": True},
            {"name": "PHA", "category_type": "Monolayer", "nominal_thickness_um": 25, "baseline_wvtr": 65.0, "baseline_otr": 300.0, "co2_permeability": 1200.0, "activation_energy_wvtr": 35.0, "activation_energy_otr": 38.0, "puncture_resistance_N": 12.0, "seal_initiation_temp_C": 100.0, "optical_haze_pct": 10.0, "cost_per_kg_inr": 550.0, "carbon_footprint_kgCO2": 1.5, "recyclability_class": "F", "fssai_certified": True},
            {"name": "Cellulose Film", "category_type": "Monolayer", "nominal_thickness_um": 20, "baseline_wvtr": 85.0, "baseline_otr": 6.5, "co2_permeability": 25.0, "activation_energy_wvtr": 28.0, "activation_energy_otr": 45.0, "puncture_resistance_N": 14.0, "seal_initiation_temp_C": 130.0, "optical_haze_pct": 3.0, "cost_per_kg_inr": 600.0, "carbon_footprint_kgCO2": 1.6, "recyclability_class": "F", "fssai_certified": True},
            {"name": "Paper/PE Laminate", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 80, "baseline_wvtr": 13.5, "baseline_otr": 5000.0, "co2_permeability": 18000.0, "activation_energy_wvtr": 35.0, "activation_energy_otr": 40.0, "puncture_resistance_N": 20.0, "seal_initiation_temp_C": 110.0, "optical_haze_pct": 100.0, "cost_per_kg_inr": 180.0, "carbon_footprint_kgCO2": 2.5, "recyclability_class": "F", "fssai_certified": True},
            {"name": "BOPP/PVDC Coated", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 25, "baseline_wvtr": 2.5, "baseline_otr": 10.0, "co2_permeability": 40.0, "activation_energy_wvtr": 42.0, "activation_energy_otr": 50.0, "puncture_resistance_N": 14.0, "seal_initiation_temp_C": 135.0, "optical_haze_pct": 6.0, "cost_per_kg_inr": 320.0, "carbon_footprint_kgCO2": 3.0, "recyclability_class": "E", "fssai_certified": True},
            {"name": "PET/AlOx", "category_type": "Barrier Core Layer", "nominal_thickness_um": 12, "baseline_wvtr": 0.8, "baseline_otr": 1.5, "co2_permeability": 6.0, "activation_energy_wvtr": 43.0, "activation_energy_otr": 41.0, "puncture_resistance_N": 28.0, "seal_initiation_temp_C": 250.0, "optical_haze_pct": 4.0, "cost_per_kg_inr": 380.0, "carbon_footprint_kgCO2": 4.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "SiOx Coated PET", "category_type": "Barrier Core Layer", "nominal_thickness_um": 12, "baseline_wvtr": 1.5, "baseline_otr": 2.2, "co2_permeability": 8.0, "activation_energy_wvtr": 42.0, "activation_energy_otr": 40.0, "puncture_resistance_N": 28.0, "seal_initiation_temp_C": 250.0, "optical_haze_pct": 5.0, "cost_per_kg_inr": 400.0, "carbon_footprint_kgCO2": 4.8, "recyclability_class": "C", "fssai_certified": True},
            {"name": "EAA", "category_type": "Heat Sealant Layer", "nominal_thickness_um": 30, "baseline_wvtr": 30.0, "baseline_otr": 5500.0, "co2_permeability": 20000.0, "activation_energy_wvtr": 35.0, "activation_energy_otr": 40.0, "puncture_resistance_N": 22.0, "seal_initiation_temp_C": 85.0, "optical_haze_pct": 6.0, "cost_per_kg_inr": 280.0, "carbon_footprint_kgCO2": 2.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "Ionomer", "category_type": "Heat Sealant Layer", "nominal_thickness_um": 30, "baseline_wvtr": 22.0, "baseline_otr": 4500.0, "co2_permeability": 16000.0, "activation_energy_wvtr": 36.0, "activation_energy_otr": 41.0, "puncture_resistance_N": 35.0, "seal_initiation_temp_C": 90.0, "optical_haze_pct": 4.0, "cost_per_kg_inr": 350.0, "carbon_footprint_kgCO2": 2.8, "recyclability_class": "C", "fssai_certified": True},
            {"name": "Wax-Coated Kraft Paper", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 100, "baseline_wvtr": 10.0, "baseline_otr": 4800.0, "co2_permeability": 17000.0, "activation_energy_wvtr": 30.0, "activation_energy_otr": 38.0, "puncture_resistance_N": 15.0, "seal_initiation_temp_C": 70.0, "optical_haze_pct": 100.0, "cost_per_kg_inr": 160.0, "carbon_footprint_kgCO2": 2.2, "recyclability_class": "F", "fssai_certified": True},
            {"name": "PE/Nylon/PE Coex", "category_type": "Monolayer", "nominal_thickness_um": 60, "baseline_wvtr": 11.0, "baseline_otr": 35.0, "co2_permeability": 140.0, "activation_energy_wvtr": 36.0, "activation_energy_otr": 48.0, "puncture_resistance_N": 45.0, "seal_initiation_temp_C": 110.0, "optical_haze_pct": 12.0, "cost_per_kg_inr": 220.0, "carbon_footprint_kgCO2": 4.5, "recyclability_class": "C", "fssai_certified": True},
            {"name": "BOPP Pearlized", "category_type": "Substrate/Print Layer", "nominal_thickness_um": 35, "baseline_wvtr": 4.5, "baseline_otr": 1600.0, "co2_permeability": 6000.0, "activation_energy_wvtr": 40.0, "activation_energy_otr": 45.0, "puncture_resistance_N": 12.0, "seal_initiation_temp_C": 140.0, "optical_haze_pct": 90.0, "cost_per_kg_inr": 165.0, "carbon_footprint_kgCO2": 2.1, "recyclability_class": "A", "fssai_certified": True}
        ]

        for p_item in polymers_data:
            db.add(Polymer(**p_item))

        db.commit()
        print("Database seeding completed successfully.")

    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()

if __name__ == '__main__':
    seed_database()
